# renew_before_expiry = 30 days
version = 3.0.1
archive_dir = /etc/letsencrypt/archive/npm-1
cert = /etc/letsencrypt/live/npm-1/cert.pem
privkey = /etc/letsencrypt/live/npm-1/privkey.pem
chain = /etc/letsencrypt/live/npm-1/chain.pem
fullchain = /etc/letsencrypt/live/npm-1/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = e9b9c7db339f6b3011ad43e3293a241c
key_type = ecdsa
elliptic_curve = secp384r1
preferred_chain = ISRG Root X1
pref_challs = dns-01, http-01
config_dir = /etc/letsencrypt
work_dir = /tmp/letsencrypt-lib
logs_dir = /tmp/letsencrypt-log
authenticator = webroot
webroot_path = /data/letsencrypt-acme-challenge,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
fullbackendapi.credenz.co.in = /data/letsencrypt-acme-challenge
