version: '3.8'

services:

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  nginx-conf:
    build:
      context: ./nginx
    ports:
      - "801:80"
    depends_on:
      - app
    restart: "on-failure"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=credenz-db.postgres.database.azure.com
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=avadhutgiri
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=Potatolovesfries<3
      - DATABASE_SSL_CA=/etc/ssl/certs/ca.pem  # Path to the certificate inside the container
    volumes:
      - ./certs/certificate.pem:/etc/ssl/certs/ca.pem:ro  # Mount the certificate file
    command: [ "node", "server.js"]
