# Upstream block for your backend
upstream app {
    server app:3000;  # This points to your app container
}

# HTTP server to listen on port 80
server {
    listen 80;
    server_name fullbackend.api.credenz.co.in;
    client_max_body_size 14M;

    # Redirect HTTP to HTTPS
    return 301 https://$host$request_uri;

    location / {
        proxy_pass http://app;  # Forward requests to the 'app' container
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
